stages:
  - gate
  - approve

variables:
  GIT_DEPTH: "0"

.clone_gate: &clone_gate
  - git clone --depth 1 "http://${GATE_DEPLOY_USER}:${GATE_DEPLOY_PASS}@gitlab.spdb.com/zh-1087/hobo-git-gate.git" /tmp/gate

gate:
  stage: gate
  tags:
    - shell
  script:
    - echo "CI_PIPELINE_SOURCE=$CI_PIPELINE_SOURCE"
    - echo "CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME"
    - echo "CI_MERGE_REQUEST_SOURCE_BRANCH_NAME=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - echo "CI_MERGE_REQUEST_TARGET_BRANCH_NAME=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - *clone_gate
    - chmod +x /tmp/gate/scripts/git_gate.sh
    - /tmp/gate/scripts/git_gate.sh
  artifacts:
    paths:
      - approval_status
    expire_in: 1h
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

approval:
  stage: approve
  tags:
    - shell
  needs:
    - git_gate
  script:
    - *clone_gate
    - chmod +x /tmp/gate/scripts/approval.sh
    - /tmp/gate/scripts/approval.sh
  when: manual
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
